Fix build with latest r2 from git

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -252,6 +252,7 @@ echo "EMAIL:       pancake@nopcode.org"
 echo "LANGS:       c"
 echo "R2_CFLAGS:   $(r2 -H R2_CFLAGS 2>/dev/null || echo '(r2 not found)')"
 echo "R2_LDFLAGS:  $(r2 -H R2_LDFLAGS 2>/dev/null || echo '(r2 not found)')"
+echo "R2_LIBS:     $(r2 -H R2_LIBS 2>/dev/null || echo '(r2 not found)')"
 echo "FLAGS:       --with-precompiled-agent"
 	exit 0
 	;;
@@ -322,7 +323,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR DESCRIPTION INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGCFG_LIBDIR PKGCFG_INCDIR PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C R2_VERSION PRECOMPILED_AGENT R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE"
+ENVWORDS="MANDIR DESCRIPTION INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGCFG_LIBDIR PKGCFG_INCDIR PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C R2_VERSION PRECOMPILED_AGENT R2_CFLAGS R2_LDFLAGS R2_LIBS HAVE_PKGCFG_R_CORE"
 
 create_environ
 
@@ -381,6 +382,16 @@ else
 	R2_LDFLAGS=""
 	echo "not found"
 	echo "ERROR: radare2 not found, r2 -H R2_LDFLAGS failed"
+	exit 1
+fi
+printf 'checking exec r2 -H R2_LIBS... '
+R2_LIBS="`r2 -H R2_LIBS 2>/dev/null`"
+if [ $? = 0 ]; then
+	echo "ok"
+else
+	R2_LIBS=""
+	echo "not found"
+	echo "ERROR: radare2 not found, r2 -H R2_LIBS failed"
 	exit 1
 fi
 SEDFLAGS=" -e '"
